export const FETCH_ITEMS_REQUEST = "FETCH_ITEMS_REQUEST";
export const FETCH_ITEMS_SUCCESS = "FETCH_ITEMS_SUCCESS";
export const FETCH_ITEMS_FAILURE = "FETCH_ITEMS_FAILURE";
export const BUY_ITEM = "BUY_ITEM";
export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
